Attempt to fix flakey tests for HTML side-by-side mode
In CI we have sometimes seen this test fail [^1] with:

```
AssertionError: expected 290 to equal 289

+ expected - actual

-290
+289
```

I haven't determined exactly where this one pixel difference comes from, but
since the actual/expected results are very close, allowing a tolerance in the
comparison is fine.

[^1]: https://github.com/hypothesis/client/actions/runs/14376354889/job/40309621923?pr=6968